#!/usr/bin/env bash

current_session=$(tmux display-message -p '#S')
sessions=$(tmux list-sessions -F '#S' | grep -v "^$current_session\$")

fzf_flags=("--border=rounded" "--border-label=$current_session")

session_picker=$(echo "$sessions" | fzf "${fzf_flags[@]}" \
    --preview="tmux list-windows -t {} -F '#W'")

if [ -n "$session_picker" ]; then
    tmux switch-client -t "$session_picker"
    exit 0
fi

# new session
session_dir=$(find ~ ~/dev -maxdepth 1 -type d 2>/dev/null | \
    fzf "${fzf_flags[@]}" --preview="lsr -c {}")
if [ -z "$session_dir" ]; then
    exit 0
fi

cd "$session_dir" || exit 1

# make sure jmattaa/scripts is installed!!!!!!!!!!
tn
